name: Clash Meta SpeedTest

on:
  schedule:
    - cron: '0 0,12 * * *'  # 每天 UTC 0点和12点运行（上海时间 8点和20点）
  workflow_dispatch:

jobs:
  test_nodes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install httpx pyyaml

      - name: Download Mihomo
        run: |
        curl -Lo mihomo.gz https://github.com/MetaCubeX/mihomo/releases/download/v1.19.4/mihomo-linux-amd64-v1.19.4.gz
          gunzip mihomo.gz
          chmod +x mihomo


      - name: Run sub.py
        run: python sub.py

      - name: Commit results
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add nodes.yml speed.txt
          git commit -m "Update nodes and speed test results" || echo "No changes"
          git push
