name: Daily IPTV + Node Speed Test

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  run_scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y jq
          pip install requests pyyaml httpx

      - name: Download Mihomo (Clash.Meta)
        run: |
          curl -Lo mihomo.gz https://github.com/MetaCubeX/mihomo/releases/download/v1.19.4/mihomo-linux-amd64-v1.19.4.gz
          gunzip mihomo.gz
          chmod +x mihomo

      - name: Run sub.py to test and filter nodes
        run: |
          echo "Running sub.py..."
          python sub.py

      - name: Commit and push results
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add nodes.yml speed.txt || true
          git commit -m 'Update nodes and speeds' || echo "No changes to commit"
          git push
